version: '3.1'

services:   
  db:
     image: mysql:5.7
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: accountowner
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always
     ports:
      - "3306:3306"
     networks:
      - mysqlnet
      - mysqlnetfpm

  web:
    build:
      context: .
    ports:
      - "5000:7909"
    image: "webapp:Debug"  

volumes:
    dbdata:


networks:
  mysqlnet:
    driver: bridge
  mysqlnetfpm:
    driver: bridge